### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mobiyan** [haseebnqureshi/serverless-shared-library#2]
Hello Haseeb,

Do you have an example of utilisation, I am trying to make this work without success. Thanks!

**Comment by haseebnqureshi** [comment]
Hey @mobiyan, thanks for finding this repo and leaving a comment. So, I'm officially deprecating this repo -- if you want to have a shred library between multiple lambda functions, there are better ways.

I would recommend that you create a private NPM module, or use NPM link to create a pseudo NPM module (without needing to publish to the NPM registry).

For a better boilerplate, head on over to my new project https://www.npmjs.com/package/serverless-hq -- that'll be much more of a help ;) 

Thanks again for dropping by -- HQ
